.\" Manpage for hello
.TH man 1 "25 October 2018" "0.1" "hello"
.SH NAME
hello \ - Greet user
.SH SYNPOSIS
hello [USERNAME]
.SH DESCRIPTION
hello greets the specified USERNAME.  If no USERNAME is specified, then the
USER environmental variable will be used.
.SH BUGS
No known bugs.
.SH AUTHOR
Peter Bui (pbui@nd.edu)
