name: Dredd

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest    
    container: pbui/cse-30872-fa21-assignments
    steps:
    - uses: actions/checkout@v2

    - name: Linting
      run:  find ${GITHUB_HEAD_REF} -type f -iname '*.*' | xargs .scripts/lint.sh 
